### ISSUE TITLE
Display warnings if remote service isn't fully functional

### ISSUE THREAD

**Issue by mjtko** [openflighthpc/flight-desktop-webapp#40]
This is the GUI side of https://github.com/openflighthpc/flight-desktop-restapi/issues/35 and https://github.com/openflighthpc/flight-desktop/issues/18.

We should display warnings if the webapp won't be able to connect to sessions due to a lack of websockets, or display screen captures due to a lack of tools.

Some sessions will not be connectable if they have been started prior to the installation of websocket support. We should mark these as such.

**Comment by benarmston** [comment]
All of these issues have been dealt with.  See https://trello.com/c/xGLgtH7N/323-required-and-perhaps-optional-dependencies-should-be-package-dependencies-of-flight-desktop-restapi; https://trello.com/c/9pPWRYVQ/399-add-screenshot-grabbing-dependencies-to-flight-desktop; https://trello.com/c/aX7cmlAF/289-desktop-restapi-should-run-flight-desktop-webify-desktop-when-needed and
